# Generated by Django 4.0.6 on 2022-10-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta_tipo', models.CharField(max_length=200)),
                ('encuesta_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('especificacion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('especificacion_dia_1', models.TextField()),
                ('especificacion_dia_2', models.TextField()),
                ('especificacion_dia_3', models.TextField()),
                ('especificacion_dia_4', models.TextField()),
                ('especificacion_dia_5', models.TextField()),
                ('especificacion_dia_6', models.TextField()),
                ('especificacion_dia_7', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_tipo', models.CharField(max_length=200)),
                ('meta_desc', models.TextField()),
                ('meta_peso_ideal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=200)),
                ('usuario_correo', models.EmailField(max_length=300)),
                ('usuario_password', models.CharField(max_length=300)),
                ('usuario_peso', models.IntegerField()),
                ('usuario_altura', models.IntegerField()),
                ('usuario_edad', models.IntegerField()),
                ('usuario_rol', models.CharField(max_length=200)),
                ('meta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.meta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.encuesta')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_check', models.BooleanField()),
                ('especificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.especificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqr_tipo', models.CharField(max_length=200)),
                ('pqr_desc', models.TextField()),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_desc', models.TextField()),
                ('plan_recomendaciones', models.TextField()),
                ('especificacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.especificacion')),
            ],
        ),
    ]
