# Generated by Django 4.0.6 on 2022-10-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_usuario_meta_id_meta_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_peso',
            field=models.FloatField(),
        ),
    ]
