# Generated by Django 4.0.6 on 2022-11-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_plan_meta_id_plan_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='meta_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='usuario_id',
        ),
    ]
