# Generated by Django 4.0.6 on 2022-11-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_plan_meta_id_plan_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='encuesta_estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
