# Generated by Django 4.0.6 on 2022-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_encuesta_encuesta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_peso',
            field=models.IntegerField(),
        ),
    ]
