# Generated by Django 4.0.6 on 2022-11-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_especificacion_especificacion_recomendaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especificacion',
            old_name='especificacion_recomendaciones',
            new_name='especificacion_recomendacion',
        ),
    ]
