# Generated by Django 4.0.6 on 2022-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_especificacion_recomendaciones_especificacion_especificacion_recomendacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='tarea_check',
            new_name='tarea_check_1',
        ),
        migrations.AddField(
            model_name='tarea',
            name='peso_check_1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='peso_check_2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='peso_check_3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='peso_check_4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_check_2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_check_3',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_check_4',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
