# Generated by Django 4.0.6 on 2022-11-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_rename_tarea_check_tarea_tarea_check_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='peso_check_4',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_fecha_avance',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_nro_semanas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
