# Generated by Django 4.0.6 on 2022-11-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_tarea_peso_check_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='peso_check_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='peso_check_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='peso_check_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='peso_check_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_4',
            field=models.BooleanField(null=True),
        ),
    ]
