# Generated by Django 4.0.6 on 2022-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_tarea_peso_check_1_alter_tarea_peso_check_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_1',
            field=models.IntegerField(null=True),
        ),
    ]
