# Generated by Django 4.0.6 on 2022-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_tarea_tarea_check_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_1',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_2',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_check_4',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
