# Generated by Django 4.0.6 on 2022-11-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_tarea_nro_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='nro_tarea',
        ),
    ]
