# Generated by Django 4.0.6 on 2022-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_remove_tarea_nro_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_nro_tarea',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
