# Generated by Django 4.0.6 on 2022-11-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_usuario_usuario_nro_tarea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioEncuesta',
        ),
    ]
