# Generated by Django 4.0.6 on 2022-11-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_delete_usuarioencuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='encuesta_estado',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='encuesta_encabezado',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
