# Generated by Django 4.0.6 on 2022-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_tip_delete_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_correo',
            field=models.EmailField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
